import React from "react";
import Head from "next/head";
import  Map  from "../components/Map.jsx";
import { useJsApiLoader } from "@react-google-maps/api";
import { Autocomplete } from "../components/Autocomplate/Autocomplate.jsx";

let MAP_KEY = process.env.NEXT_PUBLIC_MAP_KEY;

const center = {
  lat: 50.4536,
  lng: 30.5164,
};
const libraries = ["places"];


export default function Home() {
  const [search, setSearch] = React.useState(center);
  

  const { isLoaded } = useJsApiLoader({
    id: "google-map-script",
    googleMapsApiKey: MAP_KEY,
    libraries,
  });

  const onPlaceSelect = React.useCallback(coordinats => {
    setSearch(coordinats);
  }, []);

  return (
    <div className="h-screen bg-slate-400 mx-auto ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mapmarker.ico" />
      </Head>
      <div className="flex">
        <Autocomplete isLoaded={isLoaded} onSelect={onPlaceSelect} />
      </div>
      {isLoaded ? <Map center={search} /> : ""}
    </div>
  );
}

// https://www.youtube.com/watch?v=4PrpRCTxcno&t=2894s
